# Generated by Django 4.0.3 on 2022-07-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='airate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
