# Generated by Django 4.0.3 on 2022-07-12 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_cart_cartnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='currentuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
