# Generated by Django 4.0.3 on 2022-07-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_airate_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='airate',
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=50),
        ),
    ]
