# Generated by Django 4.0.3 on 2022-07-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_cart_occupied_remove_order_cart_cart_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartnumber',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
    ]
